Adds unit tests for DBHandler and MainActivity.
opendatakit/skunkworks-bat pull request #33
Opened 2019-06-24 14:00 UTC by DreamyPhobic

Following tests are covered in this:
1. SQLite Database communications test
2. Test for connection with ODK Services Database
3. QRCode Scanner Test

2019-06-30 06:29 UTC, linl33 requested changes
Overall this is a good start. There are just a few minor things. Keep adding more tests and soon we will have a robust test suite. 

In the `DBHandlerTest`, there should be a `@Before` or `@After` method that cleans the db to prevent potential interaction between the tests. In general, it is a good idea to make sure the environment in which tests start in is consistent and predictable.

Another thing that will be a problem, but don't worry about it now, is setting up ODK-X Services for the tests. Since Services needs read/write external storage permissions, they need to be granted before the tests start.

2019-06-30 06:29 UTC, linl33 commented on app/src/androidTest/java/org/odk/odknotifications/Activities/MainActivityTest.java
> +    public GrantPermissionRule grantPermissionRule = GrantPermissionRule.grant("android.permission.CAMERA");
The string literal can be replaced by `Manifest.permission.CAMERA`

2019-06-30 06:29 UTC, linl33 commented on app/src/androidTest/java/org/odk/odknotifications/Activities/MainActivityTest.java
> +                hasAction("com.google.zxing.client.android.SCAN")));
This literal can be replaced by [this constant](https://github.com/zxing/zxing/blob/ae6d7e55af0b62cd18b6ac775ce3b66caf889892/android/src/com/google/zxing/client/android/Intents.java#L39)

2019-06-30 06:29 UTC, linl33 commented on app/src/androidTest/java/org/odk/odknotifications/DatabaseCommunicator/DBHandlerTest.java
> +        dbHandler = new DBHandler(InstrumentationRegistry.getTargetContext(),null,null,1);
`getTargetContext` is deprecated, check the javadoc for replacement.

2019-06-30 06:29 UTC, linl33 commented on app/src/androidTest/java/org/odk/odknotifications/Activities/MainActivityTest.java
> +public class MainActivityTest {
This is a test that interacts with the UI, it is a good practice to annotate it with `@LargeTest`

2019-06-30 06:29 UTC, linl33 commented on app/src/androidTest/java/org/odk/odknotifications/Activities/MainActivityTest.java
> +    public GrantPermissionRule grantPermissionRule = GrantPermissionRule.grant("android.permission.CAMERA");
The `MainActivity` also needs `READ_EXTERNAL_STORAGE`

2019-07-14 20:56 UTC, DreamyPhobic commented
@linl33 @jbeorse I've made the required changes.

2019-07-20 13:44 UTC, linl33 approved these changes

2019-07-20 13:44 UTC, merged